[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    Sensirion/Sensirion I2C SEN66@1.3.1
    Sensirion/Sensirion Core@0.7.3

build_flags =
    -Wall
    -Wextra
    -std=gnu++17
