#!/usr/bin/env bash

# Verify the installed command delegates to the repository launcher, not itself.
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd -P)"
SETUP_SCRIPT="${ROOT}/scripts/setup-data-exporter.sh"
TEMP_DIR="$(mktemp -d)"
VENV="${ROOT}/services/data-exporter/.venv"
CREATED_VENV=false

cleanup() {
  rm -rf -- "${TEMP_DIR}"
  if "${CREATED_VENV}"; then
    rm -rf -- "${VENV}"
  fi
}
trap cleanup EXIT

# The repository launcher must resolve its root and pass --help to Python.
if [[ ! -x "${VENV}/bin/python" ]]; then
  mkdir -p "${VENV}/bin"
  CREATED_VENV=true
  cat >"${VENV}/bin/python" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$@"
EOF
  chmod +x "${VENV}/bin/python"
fi
"${ROOT}/scripts/omk-export" --help >"${TEMP_DIR}/repository-launcher.args"
grep -Fxq -- '-m' "${TEMP_DIR}/repository-launcher.args"
grep -Fxq -- 'data_exporter' "${TEMP_DIR}/repository-launcher.args"
grep -Fxq -- '--help' "${TEMP_DIR}/repository-launcher.args"
"${ROOT}/scripts/omk-export-usb" --status >"${TEMP_DIR}/usb-launcher.args"
grep -Fxq -- 'data_exporter.usb_cli' "${TEMP_DIR}/usb-launcher.args"
grep -Fxq -- '--status' "${TEMP_DIR}/usb-launcher.args"

# Load only the installer function, then install into a temporary stand-in for
# /usr/local/bin. This uses the same root-derived command generated by setup.
# shellcheck disable=SC1090
source <(sed -n '/^install_cli_launcher()/,/^}$/p' "${SETUP_SCRIPT}")
OMK_ROOT="${ROOT}"
SUDO=()
CLI_BIN_DIR="${TEMP_DIR}/bin"
install_cli_launcher omk-export

"${TEMP_DIR}/bin/omk-export" --dataset sen66 --from 2026-08-01 --to 2026-08-31 >"${TEMP_DIR}/installed-launcher.args"
grep -Fxq -- '--dataset' "${TEMP_DIR}/installed-launcher.args"
grep -Fxq -- 'sen66' "${TEMP_DIR}/installed-launcher.args"
grep -Fxq -- '--from' "${TEMP_DIR}/installed-launcher.args"
grep -Fxq -- '2026-08-01' "${TEMP_DIR}/installed-launcher.args"
grep -Fxq -- '--to' "${TEMP_DIR}/installed-launcher.args"
grep -Fxq -- '2026-08-31' "${TEMP_DIR}/installed-launcher.args"

echo 'PASS: repository and installed omk-export launchers resolve the repository and preserve arguments.'
