#!/usr/bin/env bash
[[ "$*" != *6* ]] || exit 0
printf 'LISTEN 0 4096 192.168.50.1%%wlan0:8000 0.0.0.0:* inet-sockopt: ( freebind )\nLISTEN 0 4096 192.168.50.1%%wlan0:1883 0.0.0.0:* inet-sockopt: ( freebind )\n'
