[platformio]
default_envs = atom-s3-lite
[env]
platform = espressif32@7.0.1
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
[env:atom-s3-lite]
board = m5stack-atoms3
board_build.sdkconfig_defaults = sdkconfig.defaults,sdkconfig.atom-s3-lite
[env:m5stick-c]
board = m5stick-c
board_build.sdkconfig_defaults = sdkconfig.defaults,sdkconfig.m5stick-c
